# Generated by Django 6.0.6 on 2026-06-19 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_number', models.CharField(max_length=50, unique=True)),
                ('duration_type', models.CharField(choices=[('15_YEARS', '15 ans'), ('30_YEARS', '30 ans'), ('PERPETUAL', 'Perpétuelle')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='graves.grave')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
