-- Schéma de la base de données - Gestion de Cimetière GI2 2026
-- Extrait réel (pg_dump --schema-only) depuis PostgreSQL (sans PostGIS)
-- après application de toutes les migrations Django.

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20),
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    mfa_code_expires_at timestamp with time zone,
    mfa_code_hash character varying(64)
);


CREATE TABLE public.cemeteries_cemetery (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    total_area numeric(12,2) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    standard_grave_length numeric(5,2) NOT NULL,
    standard_grave_width numeric(5,2) NOT NULL
);


CREATE TABLE public.blocks_block (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    area numeric(10,2) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    cemetery_id bigint NOT NULL,
    non_exploitable_area numeric(10,2) NOT NULL
);


CREATE TABLE public.graves_grave (
    id bigint NOT NULL,
    grave_number character varying(50) NOT NULL,
    length numeric(5,2) NOT NULL,
    width numeric(5,2) NOT NULL,
    capacity integer NOT NULL,
    status character varying(20) NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    block_id bigint NOT NULL,
    CONSTRAINT graves_grave_capacity_check CHECK ((capacity >= 0))
);


CREATE TABLE public.reservations_reservation (
    id bigint NOT NULL,
    reservation_date date NOT NULL,
    expiration_date date NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    grave_id bigint NOT NULL,
    validated_at timestamp with time zone,
    validated_by_id bigint
);


CREATE TABLE public.concessions_concession (
    id bigint NOT NULL,
    concession_number character varying(50) NOT NULL,
    duration_type character varying(20) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    grave_id bigint NOT NULL,
    owner_id bigint NOT NULL
);


CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method character varying(20) NOT NULL,
    reference character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    concession_id bigint NOT NULL,
    amount_due numeric(12,2)
);


CREATE TABLE public.exhumations_exhumation (
    id bigint NOT NULL,
    exhumation_date date NOT NULL,
    reason text NOT NULL,
    observations text,
    created_at timestamp with time zone NOT NULL,
    grave_id bigint NOT NULL,
    responsible_agent_id bigint,
    status character varying(20) NOT NULL,
    validated_at timestamp with time zone,
    validated_by_id bigint
);


CREATE TABLE public.audit_auditlog (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    resource character varying(100) NOT NULL,
    resource_id character varying(50),
    details text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


-- ============================================================
-- CONTRAINTES ET INDEX
-- ============================================================

ALTER TABLE public.audit_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.blocks_block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocks_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cemeteries_cemetery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cemeteries_cemetery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.concessions_concession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concessions_concession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.exhumations_exhumation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exhumations_exhumation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.graves_grave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graves_grave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.reservations_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.audit_auditlog
    ADD CONSTRAINT audit_auditlog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.blocks_block
    ADD CONSTRAINT blocks_block_code_key UNIQUE (code);

ALTER TABLE ONLY public.blocks_block
    ADD CONSTRAINT blocks_block_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cemeteries_cemetery
    ADD CONSTRAINT cemeteries_cemetery_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.concessions_concession
    ADD CONSTRAINT concessions_concession_concession_number_key UNIQUE (concession_number);

ALTER TABLE ONLY public.concessions_concession
    ADD CONSTRAINT concessions_concession_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exhumations_exhumation
    ADD CONSTRAINT exhumations_exhumation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.graves_grave
    ADD CONSTRAINT graves_grave_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_reference_key UNIQUE (reference);

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);

CREATE INDEX audit_auditlog_user_id_c1cca96c ON public.audit_auditlog USING btree (user_id);

CREATE INDEX blocks_block_cemetery_id_dd22fdf1 ON public.blocks_block USING btree (cemetery_id);

CREATE INDEX blocks_block_code_e96009cc_like ON public.blocks_block USING btree (code varchar_pattern_ops);

CREATE INDEX concessions_concession_concession_number_4812fd3c_like ON public.concessions_concession USING btree (concession_number varchar_pattern_ops);

CREATE INDEX concessions_concession_grave_id_d7bdfbcd ON public.concessions_concession USING btree (grave_id);

CREATE INDEX concessions_concession_owner_id_92534b65 ON public.concessions_concession USING btree (owner_id);

CREATE INDEX exhumations_exhumation_grave_id_35e271b0 ON public.exhumations_exhumation USING btree (grave_id);

CREATE INDEX exhumations_exhumation_responsible_agent_id_306c6560 ON public.exhumations_exhumation USING btree (responsible_agent_id);

CREATE INDEX exhumations_exhumation_validated_by_id_c1175413 ON public.exhumations_exhumation USING btree (validated_by_id);

CREATE INDEX graves_grave_block_id_33d5a428 ON public.graves_grave USING btree (block_id);

CREATE INDEX payments_payment_concession_id_bbdb4d4d ON public.payments_payment USING btree (concession_id);

CREATE INDEX payments_payment_reference_1d502039_like ON public.payments_payment USING btree (reference varchar_pattern_ops);

CREATE INDEX reservations_reservation_client_id_696a60bf ON public.reservations_reservation USING btree (client_id);

CREATE INDEX reservations_reservation_grave_id_d130df8f ON public.reservations_reservation USING btree (grave_id);

CREATE INDEX reservations_reservation_validated_by_id_d059fc86 ON public.reservations_reservation USING btree (validated_by_id);

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);

ALTER TABLE ONLY public.audit_auditlog
    ADD CONSTRAINT audit_auditlog_user_id_c1cca96c_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.blocks_block
    ADD CONSTRAINT blocks_block_cemetery_id_dd22fdf1_fk_cemeteries_cemetery_id FOREIGN KEY (cemetery_id) REFERENCES public.cemeteries_cemetery(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.concessions_concession
    ADD CONSTRAINT concessions_concession_grave_id_d7bdfbcd_fk_graves_grave_id FOREIGN KEY (grave_id) REFERENCES public.graves_grave(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.concessions_concession
    ADD CONSTRAINT concessions_concession_owner_id_92534b65_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.exhumations_exhumation
    ADD CONSTRAINT exhumations_exhumati_responsible_agent_id_306c6560_fk_users_use FOREIGN KEY (responsible_agent_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.exhumations_exhumation
    ADD CONSTRAINT exhumations_exhumati_validated_by_id_c1175413_fk_users_use FOREIGN KEY (validated_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.exhumations_exhumation
    ADD CONSTRAINT exhumations_exhumation_grave_id_35e271b0_fk_graves_grave_id FOREIGN KEY (grave_id) REFERENCES public.graves_grave(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.graves_grave
    ADD CONSTRAINT graves_grave_block_id_33d5a428_fk_blocks_block_id FOREIGN KEY (block_id) REFERENCES public.blocks_block(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_concession_id_bbdb4d4d_fk_concessio FOREIGN KEY (concession_id) REFERENCES public.concessions_concession(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reserva_validated_by_id_d059fc86_fk_users_use FOREIGN KEY (validated_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_client_id_696a60bf_fk_users_user_id FOREIGN KEY (client_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_grave_id_d130df8f_fk_graves_grave_id FOREIGN KEY (grave_id) REFERENCES public.graves_grave(id) DEFERRABLE INITIALLY DEFERRED;
