# Generated by Django 6.0.6 on 2026-06-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhumation_date', models.DateField()),
                ('reason', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='graves.grave')),
                ('responsible_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_exhumations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
