# Generated by Django 6.0.6 on 2026-07-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhumations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhumation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_exhumations', to=settings.AUTH_USER_MODEL),
        ),
    ]
