# Generated by Django 6.0.6 on 2026-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total dû pour cette concession, permet de calculer le solde restant', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Virement bancaire')], max_length=20),
        ),
    ]
