# Generated by Django 6.0.6 on 2026-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemetery',
            name='standard_grave_length',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text="Longueur standard d'un tombeau (m) pour ce cimetière", max_digits=5),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='standard_grave_width',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Largeur standard d'un tombeau (m) pour ce cimetière", max_digits=5),
        ),
    ]
